### PR TITLE
Added sync_noise call to set_input_fengs to make seeds take. Edited s…

### PR DESCRIPTION
**Pull request by AaronParsons**
…ync_noise to make it work.

### CODE REVIEW

**Review by david-deboer — COMMENTED** [review]
The line (1227 in hera_corr.py):    hosts = self.get_feng_hostnames(hosts=hosts)
is confusing.  Can the return "hosts" be made different?  Does the function cull the input list?

**Comment by david-deboer** [comment]
Maybe the input variable to  sync_noise is "requested_hosts", which get filtered through get_feng_hostnames?

**Comment by AaronParsons** [comment]
@david-deboer Somehow this commit is already merged into master? How did that happen?
Also, per the hosts comment, I think the clarity improvement is minor, and that call pattern shows up 17 places in hera_corr.py so I'd rather follow the established pattern.

**Review by david-deboer — APPROVED** [review]

**Review by david-deboer — APPROVED** [review]

**Comment by david-deboer** [comment]
I don't believe it was merged.  Should be now.

**Pull request merged**
