### PR TITLE
adding new feng with noise

### PR DESCRIPTION
**Pull request by jkocz**
Adding new FPGA programming file, that has the option gaussian noise input added. This will also require a change to the snap_fengine.py script to re-enable control of the noise input (to be submitted in separate pull request).

### CODE REVIEW

**Comment by AaronParsons** [comment]
We are still waiting on a version of this file with the interior VERSION register incremented, yes?

**Comment by jkocz** [comment]
Yes. 

This file has the added nosie source input, but still the same version number as the previous fpg file.

**Comment by jkocz** [comment]
New version is 6.0 (previous was 5.1). A major version number change was made to account for lack of backwards compatibility ones snap_fengine.py is updated to re-init the noise source on start up.

**Comment by AaronParsons** [comment]
The current version deployed on site has version 6.0 (as read from the firmware). I think this should be 7.0.

**Review by AaronParsons — APPROVED** [review]

**Review by AaronParsons — APPROVED** [review]

**Pull request merged**
